<?php
require_once __DIR__.'/../includes/bootstrap.php';
$user=require_login('traveler');
$thread=(int)($_GET['request_id']??0);if($thread<1){http_response_code(400);exit('Request is required.');}
$stmt=db()->prepare('SELECT id,request_number,destination FROM trip_requests WHERE id=? AND user_id=? LIMIT 1');$stmt->bind_param('ii',$thread,$user['id']);$stmt->execute();$request=$stmt->get_result()->fetch_assoc();if(!$request){http_response_code(404);exit('Request not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$receiver=(int)($_POST['receiver_id']??0);$message=trim($_POST['message']??'');if($receiver<1||$message===''){set_flash('danger','Recipient and message are required.');redirect('/account/messages.php?request_id='.$thread);} $stmt=db()->prepare("SELECT u.id FROM users u INNER JOIN providers p ON p.user_id=u.id INNER JOIN provider_bids b ON b.provider_id=p.id WHERE b.trip_request_id=? AND u.id=? AND b.status IN ('submitted','shortlisted','accepted') LIMIT 1");$stmt->bind_param('ii',$thread,$receiver);$stmt->execute();if(!$stmt->get_result()->fetch_assoc()){set_flash('danger','That provider is not part of this request.');redirect('/account/messages.php?request_id='.$thread);} $stmt=db()->prepare('INSERT INTO messages(sender_id,receiver_id,trip_request_id,message) VALUES(?,?,?,?)');$stmt->bind_param('iiis',$user['id'],$receiver,$thread,$message);$stmt->execute();$stmt=db()->prepare("INSERT INTO notifications(user_id,type,title,message) VALUES(?,'message','New message received',?)");$notice='You have a new message regarding '.$request['request_number'].'.';$stmt->bind_param('is',$receiver,$notice);$stmt->execute();redirect('/account/messages.php?request_id='.$thread);}
$stmt=db()->prepare("SELECT DISTINCT u.id,u.first_name,u.last_name,p.business_name FROM users u INNER JOIN providers p ON p.user_id=u.id INNER JOIN provider_bids b ON b.provider_id=p.id WHERE b.trip_request_id=? AND b.status IN ('submitted','shortlisted','accepted') ORDER BY p.business_name");$stmt->bind_param('i',$thread);$stmt->execute();$providers=$stmt->get_result();$providerList=[];while($p=$providers->fetch_assoc())$providerList[]=$p;
$stmt=db()->prepare('UPDATE messages SET is_read=1 WHERE trip_request_id=? AND receiver_id=?');$stmt->bind_param('ii',$thread,$user['id']);$stmt->execute();
$stmt=db()->prepare('SELECT m.*,u.first_name,u.last_name,p.business_name FROM messages m INNER JOIN users u ON u.id=m.sender_id LEFT JOIN providers p ON p.user_id=u.id WHERE m.trip_request_id=? AND (m.sender_id=? OR m.receiver_id=?) ORDER BY m.created_at ASC');$stmt->bind_param('iii',$thread,$user['id'],$user['id']);$stmt->execute();$messages=$stmt->get_result();
$page_title='Messages';require __DIR__.'/../includes/header.php';
?><div class="container py-5"><div class="mb-4"><h1 class="h3 mb-1">Messages</h1><p class="text-secondary mb-0"><?=e($request['request_number'])?> · <?=e($request['destination'])?></p></div><div class="card p-4 mb-4"><?php if(!$providerList):?><p class="text-secondary mb-0">Messaging becomes available when a provider submits an offer.</p><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="row g-3"><div class="col-md-4"><label class="form-label">Provider</label><select name="receiver_id" class="form-select" required><option value="">Choose provider</option><?php foreach($providerList as $p):?><option value="<?=$p['id']?>"><?=e($p['business_name'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Message</label><input name="message" class="form-control" maxlength="2000" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-dark w-100">Send</button></div></div></form><?php endif;?></div><div class="card p-4"><h2 class="h5">Conversation</h2><?php if($messages->num_rows===0):?><p class="text-secondary">No messages yet.</p><?php else:while($m=$messages->fetch_assoc()):?><div class="border-bottom py-3"><div><strong><?=e($m['business_name']?:trim($m['first_name'].' '.$m['last_name']))?></strong> <small class="text-secondary"><?=e($m['created_at'])?></small></div><div><?=e($m['message'])?></div></div><?php endwhile;endif;?></div></div><?php require __DIR__.'/../includes/footer.php'; ?>