<?php
require_once __DIR__.'/../includes/bootstrap.php';
$user=require_login('traveler');
$id=(int)($_GET['id']??$_POST['id']??0);
$stmt=db()->prepare('SELECT * FROM trip_requests WHERE id=? AND user_id=? LIMIT 1');$stmt->bind_param('ii',$id,$user['id']);$stmt->execute();$request=$stmt->get_result()->fetch_assoc();if(!$request){http_response_code(404);exit('Request not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';$now=date('Y-m-d H:i:s');
 if($action==='cancel' && in_array($request['status'],['draft','published','receiving_offers'],true)){ $stmt=db()->prepare("UPDATE trip_requests SET status='cancelled' WHERE id=? AND user_id=? AND status IN ('draft','published','receiving_offers')");$stmt->bind_param('ii',$id,$user['id']);$stmt->execute();set_flash('success','Trip request cancelled.');redirect('/account/request-view.php?id='.$id); }
 if($action==='publish' && $request['status']==='draft'){ $expires=date('Y-m-d H:i:s',time()+7*86400);$stmt=db()->prepare("UPDATE trip_requests SET status='receiving_offers',expires_at=? WHERE id=? AND user_id=? AND status='draft'");$stmt->bind_param('sii',$expires,$id,$user['id']);$stmt->execute();set_flash('success','Your request is now receiving provider offers for 7 days.');redirect('/account/request-view.php?id='.$id); }
 if($action==='extend' && in_array($request['status'],['published','receiving_offers'],true)){ $base=max(time(),strtotime($request['expires_at']??'now'));$expires=date('Y-m-d H:i:s',$base+3*86400);$stmt=db()->prepare("UPDATE trip_requests SET expires_at=?,status='receiving_offers' WHERE id=? AND user_id=? AND status IN ('published','receiving_offers')");$stmt->bind_param('sii',$expires,$id,$user['id']);$stmt->execute();set_flash('success','Request extended by 3 days.');redirect('/account/request-view.php?id='.$id); }
 set_flash('danger','That action is not available for this request.');redirect('/account/request-view.php?id='.$id);
}
$page_title='Manage Trip Request';require __DIR__.'/../includes/header.php';
?><div class="container py-5" style="max-width:900px"><div class="card p-4 p-lg-5"><div class="d-flex justify-content-between align-items-start"><div><div class="text-secondary"><?=e($request['request_number'])?></div><h1 class="h3 mb-1"><?=e($request['destination'])?></h1><p class="text-secondary mb-0"><?=e($request['start_date'])?> → <?=e($request['end_date'])?></p></div><span class="badge text-bg-light text-capitalize"><?=e(str_replace('_',' ',$request['status']))?></span></div><hr><div class="row g-3 mb-4"><div class="col-md-4"><div class="text-secondary small">Travelers</div><strong><?=((int)$request['adults']+(int)$request['children'])?></strong></div><div class="col-md-4"><div class="text-secondary small">Budget</div><strong><?=e($request['currency'])?> <?=number_format((float)$request['budget_min'])?> – <?=number_format((float)$request['budget_max'])?></strong></div><div class="col-md-4"><div class="text-secondary small">Offer deadline</div><strong><?=e($request['expires_at']?:'Not published')?></strong></div></div><?php if($request['status']==='draft'):?><div class="alert alert-info">Publish this request when you're ready for providers to compete for it.</div><form method="post" class="d-inline"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="publish"><button class="btn btn-dark">Publish & Receive Offers</button></form><?php elseif(in_array($request['status'],['published','receiving_offers'],true)):?><div class="d-flex gap-2 flex-wrap"><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="extend"><button class="btn btn-outline-dark">Extend 3 Days</button></form><form method="post" onsubmit="return confirm('Cancel this trip request?')"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="cancel"><button class="btn btn-outline-danger">Cancel Request</button></form></div><?php endif;?><div class="mt-4"><a href="/account/request-view.php?id=<?=$id?>">← Back to request</a></div></div></div><?php require __DIR__.'/../includes/footer.php'; ?>