<?php
require_once __DIR__.'/../includes/bootstrap.php';
$user=require_login('traveler');$id=(int)($_GET['id']??0);
$stmt=db()->prepare('SELECT * FROM trip_requests WHERE id=? AND user_id=? LIMIT 1');$stmt->bind_param('ii',$id,$user['id']);$stmt->execute();$request=$stmt->get_result()->fetch_assoc();if(!$request){http_response_code(404);exit('Request not found.');}
$stmt=db()->prepare('SELECT b.*,p.business_name,p.verification_status,p.rating FROM provider_bids b JOIN providers p ON p.id=b.provider_id WHERE b.trip_request_id=? AND b.status IN (\'submitted\',\'shortlisted\',\'accepted\') ORDER BY b.total_amount ASC');$stmt->bind_param('i',$id);$stmt->execute();$bids=$stmt->get_result();
$page_title='Request '. $request['request_number'];require __DIR__.'/../includes/header.php';
?><div class="container py-5"><div class="d-flex justify-content-between mb-4"><div><h1 class="h3 mb-1"><?=e($request['request_number'])?></h1><p class="text-secondary mb-0"><?=e($request['origin'])?> → <?=e($request['destination'])?> · <?=e($request['start_date'])?> to <?=e($request['end_date'])?></p></div><span class="badge text-bg-light align-self-start p-2"><?=e(str_replace('_',' ',$request['status']))?></span></div>
<div class="card p-4 mb-4"><div class="row"><div class="col-md-3"><strong>Travelers</strong><br><?=e((string)$request['adults'])?> adults, <?=e((string)$request['children'])?> children</div><div class="col-md-3"><strong>Budget</strong><br>₹<?=number_format((float)$request['budget_min'])?> – ₹<?=number_format((float)$request['budget_max'])?></div><div class="col-md-3"><strong>Style</strong><br><?=e($request['travel_type']?:'Flexible')?></div><div class="col-md-3"><strong>Requirements</strong><br><?=e($request['description']?:'Not specified')?></div></div></div>
<h2 class="h4 mb-3">Provider offers (<?=$bids->num_rows?>)</h2><?php if($bids->num_rows===0):?><div class="card p-4 text-secondary">No offers yet. Your request is live and eligible providers can submit bids.</div><?php else: while($b=$bids->fetch_assoc()):?><div class="card p-4 mb-3"><div class="row align-items-center"><div class="col-md-6"><h3 class="h5 mb-1"><?=e($b['business_name'])?></h3><div class="text-secondary">★ <?=number_format((float)$b['rating'],1)?> · <?=e($b['verification_status'])?></div><p class="mt-2 mb-0"><?=e($b['description']?:'No description provided.')?></p></div><div class="col-md-3 text-md-end"><div class="price">₹<?=number_format((float)$b['total_amount'])?></div><div class="text-secondary">Offer total</div></div><div class="col-md-3 text-md-end"><?php if($b['status']==='accepted'): ?><a class="btn btn-success mt-3 mt-md-0" href="/account/booking-view.php?bid=<?=$b['id']?>">View booking</a><?php elseif(in_array($request['status'],['receiving_offers','published'],true)): ?><form method="post" action="/account/accept-bid.php" onsubmit="return confirm('Accept this provider offer and create the booking?');"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="bid_id" value="<?=$b['id']?>"><button class="btn btn-dark mt-3 mt-md-0">Accept offer</button></form><?php endif; ?></div></div></div><?php endwhile;endif;?></div><?php require __DIR__.'/../includes/footer.php'; ?>
