<?php
require_once __DIR__.'/../includes/bootstrap.php';
$user=require_login('provider');$requestId=(int)($_GET['request_id']??$_POST['request_id']??0);
$stmt=db()->prepare('SELECT * FROM trip_requests WHERE id=? AND status IN (\'published\',\'receiving_offers\') AND expires_at>NOW() LIMIT 1');$stmt->bind_param('i',$requestId);$stmt->execute();$request=$stmt->get_result()->fetch_assoc();if(!$request){http_response_code(404);exit('Request not available.');}
$stmt=db()->prepare('SELECT id,business_name FROM providers WHERE user_id=? LIMIT 1');$stmt->bind_param('i',$user['id']);$stmt->execute();$provider=$stmt->get_result()->fetch_assoc();
$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf($_POST['csrf_token']??null);$amount=(float)($_POST['total_amount']??0);$desc=trim($_POST['description']??'');$valid=$_POST['valid_until']??null;if($amount<=0){$error='Enter a valid offer amount.';}else{$number='BID'.date('ymd').strtoupper(bin2hex(random_bytes(3)));$stmt=db()->prepare('INSERT INTO provider_bids (trip_request_id,provider_id,bid_number,total_amount,currency,description,valid_until,status) VALUES (?,?,?,?,?,?,?,\'submitted\')');$currency='INR';$stmt->bind_param('iisdsss',$requestId,$provider['id'],$number,$amount,$currency,$desc,$valid);try{$stmt->execute();flash('success','Offer '.$number.' submitted successfully.');redirect('/provider/dashboard.php');}catch(mysqli_sql_exception $e){$error='You have already submitted an offer for this request.';}}}
$page_title='Submit Offer';require __DIR__.'/../includes/header.php';
?><div class="container py-5" style="max-width:800px"><div class="card p-4 p-lg-5"><h1 class="h3">Submit offer for <?=e($request['request_number'])?></h1><p class="text-secondary"><?=e($request['origin'])?> → <?=e($request['destination'])?> · <?=e($request['start_date'])?> to <?=e($request['end_date'])?></p><div class="alert alert-light">Traveler budget: ₹<?=number_format((float)$request['budget_min'])?> – ₹<?=number_format((float)$request['budget_max'])?><br><strong>Requirements:</strong> <?=e($request['description']?:'Not specified')?></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="request_id" value="<?=$requestId?>"><label class="form-label">Your total offer (INR)</label><input class="form-control mb-3" type="number" step="0.01" min="1" name="total_amount" required><label class="form-label">Offer valid until</label><input class="form-control mb-3" type="datetime-local" name="valid_until"><label class="form-label">Proposal</label><textarea class="form-control" name="description" rows="6" placeholder="Hotels, inclusions, transfers, activities, cancellation terms..."></textarea><button class="btn btn-dark mt-4">Submit Offer</button></form></div></div><?php require __DIR__.'/../includes/footer.php'; ?>
