<?php
require_once __DIR__.'/../includes/bootstrap.php';
$user=require_login('provider');
$stmt=db()->prepare('SELECT id,business_name,verification_status,rating,response_rate,cancellation_rate FROM providers WHERE user_id=? LIMIT 1');$stmt->bind_param('i',$user['id']);$stmt->execute();$provider=$stmt->get_result()->fetch_assoc();
if(!$provider){exit('Provider profile not found.');}
$page_title='Provider Dashboard';require __DIR__.'/../includes/header.php';
if($provider['verification_status']==='pending'): ?><div class="container py-5"><div class="card p-4"><h1 class="h4">Provider account pending verification</h1><p class="text-secondary mb-0">Your business profile has been created. Once NamVoy verifies your business, matching RFQs will appear here.</p></div></div><?php require __DIR__.'/../includes/footer.php'; exit; ?><?php endif;
$stmt=db()->prepare("SELECT tr.*, (SELECT COUNT(*) FROM provider_bids pb WHERE pb.trip_request_id=tr.id AND pb.provider_id=?) AS already_bid FROM trip_requests tr WHERE tr.status IN ('published','receiving_offers') AND tr.expires_at > NOW() ORDER BY tr.created_at DESC");$stmt->bind_param('i',$provider['id']);$stmt->execute();$requests=$stmt->get_result();
?>
<div class="container py-5"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1"><?=e($provider['business_name'])?></h1><p class="text-secondary mb-0">Verification: <?=e($provider['verification_status'])?> · Rating <?=number_format((float)$provider['rating'],1)?></p></div></div><div class="row g-3 mb-4"><div class="col-md-4"><div class="card p-3 stat-card"><div class="text-secondary">Response rate</div><div class="h3 mb-0"><?=number_format((float)$provider['response_rate'],0)?>%</div></div></div><div class="col-md-4"><div class="card p-3 stat-card"><div class="text-secondary">Cancellation rate</div><div class="h3 mb-0"><?=number_format((float)$provider['cancellation_rate'],0)?>%</div></div></div></div><div class="card"><div class="card-body"><h2 class="h5">Matching travel requests</h2><?php if($requests->num_rows===0):?><p class="text-secondary mb-0">No open requests right now.</p><?php else:?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Request</th><th>Destination</th><th>Dates</th><th>Budget</th><th></th></tr></thead><tbody><?php while($r=$requests->fetch_assoc()):?><tr><td><?=e($r['request_number'])?></td><td><?=e($r['destination'])?></td><td><?=e($r['start_date'])?> → <?=e($r['end_date'])?></td><td>₹<?=number_format((float)$r['budget_max'])?></td><td><?php if($r['already_bid']):?><span class="text-secondary">Bid submitted</span><?php else:?><a class="btn btn-sm btn-dark" href="/provider/bid-add.php?request_id=<?=$r['id']?>">Submit offer</a><?php endif;?></td></tr><?php endwhile;?></tbody></table></div><?php endif;?></div></div></div>
<?php require __DIR__.'/../includes/footer.php'; ?>
