<?php
require_once __DIR__.'/../includes/bootstrap.php';
$user=require_login('provider');
$providerStmt=db()->prepare('SELECT id FROM providers WHERE user_id=? LIMIT 1');$providerStmt->bind_param('i',$user['id']);$providerStmt->execute();$provider=$providerStmt->get_result()->fetch_assoc();if(!$provider)exit('Provider profile not found.');
$thread=(int)($_GET['request_id']??0);if($thread<1){http_response_code(400);exit('Request is required.');}
$stmt=db()->prepare('SELECT tr.id,tr.request_number,tr.destination,tr.user_id FROM trip_requests tr INNER JOIN provider_bids b ON b.trip_request_id=tr.id WHERE tr.id=? AND b.provider_id=? AND b.status IN (\'submitted\',\'shortlisted\',\'accepted\') LIMIT 1');$stmt->bind_param('ii',$thread,$provider['id']);$stmt->execute();$request=$stmt->get_result()->fetch_assoc();if(!$request){http_response_code(404);exit('Request not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$message=trim($_POST['message']??'');if($message===''){set_flash('danger','Message is required.');redirect('/provider/messages.php?request_id='.$thread);} $receiver=(int)$request['user_id'];$stmt=db()->prepare('INSERT INTO messages(sender_id,receiver_id,trip_request_id,message) VALUES(?,?,?,?)');$stmt->bind_param('iiis',$user['id'],$receiver,$thread,$message);$stmt->execute();redirect('/provider/messages.php?request_id='.$thread);}
$stmt=db()->prepare('SELECT m.*,u.first_name,u.last_name,p.business_name FROM messages m INNER JOIN users u ON u.id=m.sender_id LEFT JOIN providers p ON p.user_id=u.id WHERE m.trip_request_id=? AND (m.sender_id=? OR m.receiver_id=?) ORDER BY m.created_at ASC');$stmt->bind_param('iii',$thread,$user['id'],$user['id']);$stmt->execute();$messages=$stmt->get_result();
$page_title='Messages';require __DIR__.'/../includes/header.php';
?><div class="container py-5"><div class="mb-4"><h1 class="h3 mb-1">Traveler conversation</h1><p class="text-secondary mb-0"><?=e($request['request_number'])?> · <?=e($request['destination'])?></p></div><div class="card p-4 mb-4"><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="row g-3"><div class="col-md-10"><label class="form-label">Message</label><input name="message" class="form-control" maxlength="2000" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-dark w-100">Send</button></div></div></form></div><div class="card p-4"><h2 class="h5">Conversation</h2><?php if($messages->num_rows===0):?><p class="text-secondary">No messages yet.</p><?php else:while($m=$messages->fetch_assoc()):?><div class="border-bottom py-3"><div><strong><?=e($m['business_name']?:trim($m['first_name'].' '.$m['last_name']))?></strong> <small class="text-secondary"><?=e($m['created_at'])?></small></div><div><?=e($m['message'])?></div></div><?php endwhile;endif;?></div></div><?php require __DIR__.'/../includes/footer.php'; ?>
